name: 'Terraform AWS Infrastructure'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: AKIAX3NVJFI7M3VUYB3C                             
          aws-secret-access-key: nIrU5M0fnnf4zTeBJ3qBBCSHcJxA2LN4C2138/J                                               #${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform/EKS
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/EKS
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform/EKS
        run: terraform apply -auto-approve
      - name: Terraform Output
        working-directory: terraform/EKS
        run: terraform output
